### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks @dvrkps. Would you say a bit about why you'd like to support all 1.x versions of Go for this library?

**Comment by kytrinyx** [comment]
Ah, I found the documentation about this change.

In the future, I would recommend adding context about what your change does and why it would be an improvement—even if the change is small or seems obvious to you.

I would prefer to support tip, 1.9, and 1.8 (latest stable release and previous stable release), and update manually after each release so that we know that the codebase works with the newest release.

**Comment by dvrkps** [comment]
@kytrinyx done.

**Comment by kytrinyx** [comment]
Thanks!

**Pull request merged**
